title: Blog Bibliotheks- und Archivinformatik
author: Martin
email: martin.heeb@stud.fhgr.ch
description: > # this means to ignore newlines
  Vorlage für ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020

# social links


show_excerpts: false # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
